# Generated by Django 4.1.7 on 2023-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('competencia', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=40))

            ],
        ),
    ]
