# Generated by Django 4.1.7 on 2023-04-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalDoPreparada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionais',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
